version: 2
sources:
  - name: rds
    database: northwinds
    schema: public
    tables:
      - name: customers
      - name: suppliers
      - name: shippers
      - name: orders
      - name: order_details